name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

     # https://github.com/actions/setup-node
    - name: Setup node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm
 
    - name: Install dependencies
      run: npm install

    - name: Cache playwright binaries
      uses: actions/cache@v2
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{ hashFiles('./node_modules/playwright/package.json') }}

    - name: Install playwright deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
